// Package relation defines the core Relation domain type for Repro.
//
// Relations are directed edges in the dependency and usage graph.
// They connect Entity nodes and express how components depend on, use, or affect
// one another.
package relation

import (
	"github.com/BaimPriyatna/repro/src/core/entity"
)

// Kind classifies the type of relationship between two entities.
type Kind string

const (
	// KindDependsOn expresses a direct dependency edge: A requires B at runtime
	// or build time.
	KindDependsOn Kind = "depends_on"

	// KindImports expresses a source-level import: A imports B in code.
	KindImports Kind = "imports"

	// KindUses expresses a usage relationship: A uses B at runtime (e.g. calls
	// an external tool or reads a config).
	KindUses Kind = "uses"

	// KindGeneratedBy expresses a provenance edge: A was generated by B.
	KindGeneratedBy Kind = "generated_by"

	// KindConfiguredBy expresses a configuration edge: A is configured by B.
	KindConfiguredBy Kind = "configured_by"

	// KindOwnedBy expresses an ownership edge: A is owned/managed by B.
	KindOwnedBy Kind = "owned_by"

	// KindAffects expresses a causal edge: a change in A may affect B.
	KindAffects Kind = "affects"
)

// ID is a stable, unique relation identifier within the local store.
type ID string

// Relation is a directed edge between two entities in the RepairMap graph.
//
// Relations are immutable once stored and must not be silently modified.
type Relation struct {
	// ID is the unique identifier for this relation.
	ID ID `json:"id"`

	// Kind classifies what type of relationship this represents.
	Kind Kind `json:"kind"`

	// FromID is the source entity (the dependent or user).
	FromID entity.ID `json:"from_id"`

	// ToID is the target entity (the dependency or resource being used).
	ToID entity.ID `json:"to_id"`

	// Attributes holds optional, kind-specific metadata about the relationship.
	// The storage layer must preserve unknown keys.
	Attributes map[string]any `json:"attributes,omitempty"`
}

// Involves reports whether the relation is connected to the given entity ID,
// either as source or target.
func (r *Relation) Involves(id entity.ID) bool {
	return r.FromID == id || r.ToID == id
}
